### ISSUE TITLE
why is robot not ready to execute buzz script?

### ISSUE THREAD

**Issue by alacalcasis** [MISTLab/BuzzKH4#3]
When trying to run testbuzzexperiment.argos for khepera iv i get: "Robot is not ready to execute Buzz script."

Any idea why? Thank you in advance!

PD: this of course after installing khepera iv plugin for argos3 and BuzzKH4.

**Comment by vivek-shankar** [comment]
Hi Alan Calderon Castro, 

Thank you for your interest in Buzz. 

You are getting this error because this Argos file does not specify a buzz script to be executed. 
You could specify the buzz script you want the robots to execute as follows: 
        ```<params
              bytecode_file="test.bo"
                debug_file="test.bdb">
                <wheel_turning
                hard_turn_angle_threshold="90"
                soft_turn_angle_threshold="70"
                no_turn_angle_threshold="0.5"
                max_speed="10"/>
        </params>```
  Replacing this https://github.com/ilpincy/argos3-kheperaiv/blob/master/src/testing/testbuzzexperiment.argos#L34 (line 34-39) in the testbuzzexperiment.argos file. 
Before you run the .argos file make sure to compile the test.bzz file in the same folder. You could compile this buzz script using the following command "bzzc test.bzz". 
This script should move the robot forward. 
For more information on writing your own buzz script, you can refer to https://the.swarming.buzz/
Please feel free to contact me if you have any further questions. 

With best regards,
Vivek

**Comment by alacalcasis** [comment]
Thank you very much Vivek! It worked! 
The khepera IV shows three beams of light, pink at its left and right, and cyan at its front, what do they simbolize?
Cheers,

Alan

**Comment by alacalcasis** [comment]
Thank you very much Vivek! It worked!
